version: "3.8"
services:
  db:
    image: amd64/mysql:8
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: /run/secrets/db_mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
        - db_root_password
        - db_password
        - db_mysql_user
  wordpress:
    depends_on:
      - db
    image: amd64/wordpress:6
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER_FILE: /run/secrets/db_mysql_user
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
      - db_mysql_user


secrets:
  db_password:
    file: db_password.txt
  db_root_password:
    file: db_root_password.txt
  db_mysql_user:
    file: db_mysql_user.txt
volumes:
  db_data:
