Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-20.04"
  
  config.vm.define "server" do |server|
    server.vm.provider "virtualbox" do |vb_server|
    vb_server.memory = "4096"
    vb_server.cpus = "3"
    end
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.10.100"
    server.vm.provision :shell, :path => ".provision/upserver.sh"
  end
  config.vm.define "node" do |node|
    node.vm.hostname = "node"
    node.vm.network "private_network", ip: "192.168.12.102"
    node.vm.provision "shell", inline: <<-SHELL
      sudo apt update
      sudo sed -i '10 a192.168.10.100 server' /etc/hosts
      sudo sed -i '11 a192.168.11.101 client' /etc/hosts
      sudo sed -i '12 a192.168.12.102 node' /etc/hosts
    SHELL
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "192.168.11.101"
    client.vm.provision :shell, :path => ".provision/mysql.sh"
  end
end
